# .github/workflows/metrics.yml
name: Base_Metrics
on:
  # Daily at 16:00 UTC
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 10 * * *"
    - cron: "0 16 * * *"
    - cron: "0 22 * * *"
  # Manual trigger from the Actions tab
  workflow_dispatch:

permissions:
  contents: write     # to push updates / create PRs
  actions: read       # to run actions

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your profile repo
      - name: 🦑 Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # 2️⃣ Install jq (required by lowlighter/metrics)
      - name: 🦑 Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # 3️⃣ Followup
      - name: 🦑 Followup
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: user: iamAntimPal
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          base_hireable: yes
          output_action: gist
          committer_gist: ${{ secrets.WORKFLOW_GIST }}
          
