# .github/workflows/metrics.yml
name: Code
on:
      pull_request:
        branches:
          - main            # ✅ Change this if your default branch is different
      workflow_dispatch:
  # Daily at 16:00 UTC
  # schedule:
  #   - cron: "0 0 * * *"
  #   - cron: "0 10 * * *"
  #   - cron: "0 16 * * *"
  #   - cron: "0 22 * * *"
  # Manual trigger from the Actions tab
  

permissions:
  contents: write     # to push updates / create PRs
  actions: read       # to run actions

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your profile repo
      - name: 🦑 Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # 2️⃣ Install jq (required by lowlighter/metrics)
      - name: 🦑 Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Code
      - name: 🐙Code
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.WORKFLOW_GIST }}
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_visibility: public
          plugin_code_languages: python 


      # 9️⃣ Commit & push all SVG updates to a PR
      - name: 🦑 Commit & Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          branch: metrics-update
          title: "chore: update all metrics SVGs"
          body: "Auto-generated metrics via lowlighter/metrics"
