name: Python and C++ Snippet of the Day

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-snippet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Add step to install dependencies
      - name: Install Missing Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io jq

      - name: Generate Code Snippet Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_languages: 'python,cpp'    # ✅ Make sure this is a string
          plugin_code_load: 400
