# Read the full reference here: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Follow up Issues and PRs
on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push: { branches: ["master", "main", "metrics"] }

permissions:
  contents: read             # required for checkout and metadata
  issues: write              # required for interacting with issues
  pull-requests: write       # required for PR-based metrics
  
jobs:
  follow-up-pr-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io jq
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
