# .github/workflows/metrics.yml

name: Metrics

on:
  schedule:
    - cron: "0 16 * * *"  # Daily at 16:00 UTC
  workflow_dispatch:      # Manual trigger from GitHub Actions tab

permissions:
  contents: write         # Allows pushing updates / creating PRs
  actions: read           # Allows running actions

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your profile repository
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # 2️⃣ Install jq (required for metrics action)
      - name: 🛠️ Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # 3️⃣ Generate GitHub Reactions metrics SVG
      - name: 💬 Generate Reactions metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.reactions.svg
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
